rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head

env:
  - RAILS_VERSION=3.0.11
  - RAILS_VERSION=3.1.3
  - RAILS_VERSION=3.2.1
  - RAILS_VERSION=3-0-stable
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable
  #- RAILS_VERSION=master

matrix:
  exclude:
    - rvm: 1.9.2
      env: RAILS_VERSION=master
    - rvm: 1.8.7
      env: RAILS_VERSION=master
